##############################################################################
#  Copyright Christopher Kormanyos 2023.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: mp_cpp
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  gcc-native:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        standard: [ c++11, c++20 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: gcc-native
        run: |
          make STD=${{ matrix.standard }} --jobs=8 all
          ls -la ./unix/bessel.exe ./unix/gamma.exe ./unix/ln2.exe ./unix/pi.exe ./unix/test.exe
          ./unix/pi.exe
          grep '5779458151' ./unix/pi.out
