##############################################################################
#  Copyright Christopher Kormanyos 2023.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: mp_cpp
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  gcc-native:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        standard: [ c++11, c++20 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: gcc-native
        run: |
          make STD=${{ matrix.standard }} --jobs=8 all
          ls -la ./unix/bessel.exe ./unix/gamma.exe ./unix/ln2.exe ./unix/pi.exe ./unix/test.exe
          ./unix/pi.exe
          grep '5779458151' ./unix/pi.out
  macos-native:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        standard: [ c++11, c++20 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: macos-native
        run: |
          make STD=${{ matrix.standard }} --jobs=8 all
          ls -la ./unix/bessel.exe ./unix/gamma.exe ./unix/ln2.exe ./unix/pi.exe ./unix/test.exe
          ./unix/pi.exe
          grep '5779458151' ./unix/pi.out
  msvc-release-x64:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        example: [ Bessel, Gamma, Ln2, Pi, Test ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2
      - name: msvc-release-x64
        shell: cmd
        working-directory: ./
        run: |
          set INCLUDE=%cd%\fft\FFTW\215\fftw;%cd%\fft\FFTW\215\rfftw;%cd%\fft\FFTW\215\threads;%cd%;%INCLUDE%
          MSBuild -m mp_cpp.sln -p:useenv=true -p:Configuration=${{ matrix.example }}_Exe_Release -p:Platform=x64 /t:Rebuild
          dir %cd%\_Out\mp_cpp\x64\${{ matrix.example }}_Exe_Release\${{ matrix.example }}_Exe_Release.exe
          %cd%\_Out\mp_cpp\x64\Pi_Exe_Release\Pi_Exe_Release.exe
